proof of concept
hixi/docker-postgres-pgtap pull request #1
Opened 2016-11-09 16:59 UTC by hixi

@das-g please have a look ;-)

2016-11-11 09:32 UTC, hixi commented
@das-g makes it easier to review, but your comments were lost ^^

2016-11-11 09:39 UTC, das-g requested changes

2016-11-11 09:39 UTC, das-g commented on docker-compose.yml
> +  #     - "pgtap:postgres"
remove or (test and) reactivate commented-out code

2016-11-11 09:39 UTC, das-g commented on examples/angproj/01-tests/dummy-test.sql
> +\set QUIET 1
Has `QUIET 1` not already been set on line 2?

2016-11-11 09:39 UTC, das-g commented on examples/angproj/01-tests/test_results.txt
> +/examples/01-tests/dummy-test.sql ..
Should this (result?) file be checked in at all?

2016-11-11 09:39 UTC, das-g commented on scripts/reset_db.sql
> +
Is this as-of-yet empty section going to be populated?

2016-11-11 09:39 UTC, das-g commented on scripts/create_pg_tap_extension.sh
> +set -e
:+1:

2016-11-11 09:39 UTC, das-g commented on scripts/reset_database.sh
> +psql -U postgres -h postgres < /opt/bin/reset_db.sql
Should we `set -e` here, too?

2016-11-11 09:39 UTC, das-g commented on run_test.sh
> +set -e
:+1:

2016-11-30 12:11 UTC, hixi commented on examples/angproj/01-tests/test_results.txt
> +/examples/01-tests/dummy-test.sql ..
Yes, this is just an example usage.

2016-11-30 12:13 UTC, hixi commented on scripts/reset_db.sql
> +
the reset script does not work, I'm probably better off removing it than committing something broken...

2016-11-30 12:17 UTC, merged